# Generated by Django 5.1.6 on 2025-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_slug_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
