# Generated by Django 5.1.6 on 2025-04-08 05:58

import api.models.products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', validators=[api.models.products.validate_image_extension]),
        ),
    ]
