# Generated by Django 5.1.6 on 2025-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
