# Generated by Django 5.1.6 on 2025-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
