# Generated by Django 5.1.6 on 2025-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_branch_city_branch_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
    ]
