# Generated by Django 5.1.6 on 2025-05-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_price_product_original_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'branch', 'color')},
        ),
    ]
