# Generated by Django 5.1.6 on 2025-05-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cart_user_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='vnp_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
