# Generated by Django 5.1.6 on 2025-05-31 02:41

import api.models.products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_product_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=api.models.products.product_image_upload_path),
        ),
    ]
